version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "18:00"
      timezone: "Europe/Berlin"
    reviewers:
      - segebre
    assignees:
      - segebre
    # commit-message:
    #   prefix: "[Dependabot]"
    #   prefix-development: "[Dependabot] devDependencies"
    #   include: "scope"
    pull-request-branch-name:
      separator: "-"